### ISSUE TITLE
Product import doesn't allow empty attribute values for non-static attributes

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#86] opened 2018-01-03 15:59 UTC
_From @jarnooravainen on June 20, 2017 9:29_

### Preconditions

1. Magento 2.1.8
2. Product attribute has non-empty value in the DB
3. In the import file product attribute's value is empty

### Steps to reproduce

1. Run product import
2. Check product attribute's value in the DB

### Expected result

1. Product attribute's value is empty after the import

### Actual result

1. Product attribute's value is not updated to empty

Seems bit odd behaviour that attribute's value cannot be updated to empty via product import. System doesn't allow empty values to be set for non-static attributes.

\Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType:

```
public function clearEmptyData(array $rowData)
{
    foreach ($this->_getProductAttributes($rowData) as $attrCode => $attrParams) {
        if (!$attrParams['is_static'] && empty($rowData[$attrCode])) {
            unset($rowData[$attrCode]);
        }
    }
    return $rowData;
}
```
My suggestion is that shouldn't the product import check allowed values for the attribute instead of just checking if attribute is static or non-empty. This prevents also updating zero integer as a value, obviously.

_Copied from original issue: magento/magento2#9990_

**Comment by piotrekkaminski** [comment] 2018-01-03 15:59
_From @veloraven on June 21, 2017 13:15_

@jarnooravainen thank you for your feedback.
Please provide exact detailed steps, with attributes examples.
Please also specify exact Magento version you are using.

**Comment by piotrekkaminski** [comment] 2018-01-03 15:59
_From @koenner01 on June 23, 2017 11:27_

@jarnooravainen https://github.com/magento/magento2/issues/10006, https://github.com/magento/magento2/issues/7468

**Comment by piotrekkaminski** [comment] 2018-01-03 15:59
_From @magento-engcom-team on September 20, 2017 8:59_

@jarnooravainen We added Magento version into preconditions.

**Comment by piotrekkaminski** [comment] 2018-01-03 15:59
_From @magento-engcom-team on September 20, 2017 9:2_

@jarnooravainen, thank you for your report.
We've created internal ticket(s) MAGETWO-75556 to track progress on the issue.

**Comment by dmanners** [comment] 2018-01-17 08:24
Duplicate of https://github.com/magento-engcom/import-export-improvements/issues/49

**Closed as completed by dmanners** 2018-01-17 08:24 UTC
Labels: acknowledged
