### ISSUE TITLE
ImportExport Custom option dropdown with price 0 causing indexer issues

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#52] opened 2017-11-06 17:21 UTC
_From @paales on September 21, 2016 20:26_

### Preconditions

1. 2.1.0
### Steps to reproduce

1. Create an import with a dropdown option that is required.
2. Add an option with the price 0
### Expected result

1. The catalog price shouldn't increase.
### Actual result

1. Catalog price increases, because it selects the lowest price from `catalog_product_option_type_price` but the value isn't inserted.

This line should be `isset()` instead of `!empty()`:
https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1618

_Copied from original issue: magento/magento2#6701_

**Comment by piotrekkaminski** [comment] 2017-11-06 17:21
_From @asemenenko on September 22, 2016 14:54_

Needs to be fixed also in #4808  and #4092 at the same time.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:21
_From @IlnitskiyArtem on June 29, 2017 13:24_

@paales, We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:21
_From @paales on June 29, 2017 15:6_

@IlnitskiyArtem  Take a look at the code: https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1617

On this line it checks if the value isn't empty, but the string `'0'` IS empty. It should just check if that value exists instead requiring a truthy value.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:21
_From @IlnitskiyArtem on June 29, 2017 15:25_

@paales, Thanks for the feedback.
We've created internal ticket MAGETWO-70354 to address this issue.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:21
_From @magento-engcom-team on September 25, 2017 22:0_

@paales, thank you for your report.
We've created internal ticket(s) MAGETWO-70354, MAGETWO-73121 to track progress on the issue.

**Comment by umarch06** [comment] 2018-01-04 10:13
@dmanners

**Comment by umarch06** [comment] 2018-01-09 08:08
I tried to reproduce the steps, catalog price didn’t increase when I added value to a custom option with price zero. So it is working fine if either I import product options or create new while creating/updating current product. It needs to be rechecked.

**Comment by TomashKhamlai** [comment] 2018-01-09 12:09
I was not able to reproduce this issue.
@umarch-rltsquare, @dmanners I tested Magento CE from 2.3-develop branch. I attached the archive with CSV and video.
[price0_product_20180109_094835.tar.gz](https://github.com/magento-engcom/import-export-improvements/files/1614999/price0_product_20180109_094835.tar.gz)

**Comment by dmanners** [comment] 2018-01-09 12:38
Thank you @TomashKhamlai and @umarch-rltsquare for looking into this problem. Since we are supporting 2.3-develop in this project I will close this issue now.

**Closed by dmanners** 2018-01-09 12:38 UTC
Labels: good first issue, high priority
