### ISSUE TITLE
Change the value of visibility

### ISSUE THREAD

**Issue by PieterCappelle** [magento-engcom/import-export-improvements#5] opened 2017-10-14 15:25 UTC
If your Magento2 adminhtml is in dutch the value of the column visiblity must be 'Catalogus, Zoeken' instead of 'Catalog, Search'. When you run CSV by command line the value must be Catalog, Search. We should not use strings but constants or easier, VISIBILITY_NOT_VISIBLE = 1, VISIBILITY_IN_CATALOG = 2, VISIBILITY_IN_SEARCH = 3, VISIBILITY_BOTH = 4.

**Comment by dmanners** [comment] 2017-12-01 16:59
Duplicate of https://github.com/magento-engcom/import-export-improvements/issues/61

**Closed by dmanners** 2017-12-01 16:59 UTC
