### ISSUE TITLE
Clean up Model/Import file (PHPStan)

### ISSUE THREAD

**Issue by dmanners** [magento-engcom/import-export-improvements#121] opened 2018-10-25 14:07 UTC
### Preconditions (*)

1. 2.3-develop
2. phpstan installed and run against app/code/Magento/ImportExport

### Steps to reproduce (*)

1. run `./vendor/bin/phpstan analyse -l 0 app/code/Magento/ImportExport/`

### Expected result (*)

1. No Errors

### Actual result (*)

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Line   Model/Import.php
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------
  206    Access to an undefined property Magento\ImportExport\Model\Import::$_coreConfig.
  216    Access to an undefined property Magento\ImportExport\Model\Import::$importHistoryModel.
  217    Access to an undefined property Magento\ImportExport\Model\Import::$localeDate.
  418    Access to an undefined property Magento\ImportExport\Model\Import::$importHistoryModel.
  437    Access to an undefined property Magento\ImportExport\Model\Import::$importHistoryModel.
  439    Access to an undefined property Magento\ImportExport\Model\Import::$importHistoryModel.
  733    Access to an undefined property Magento\ImportExport\Model\Import::$localeDate.
  745    Access to an undefined property Magento\ImportExport\Model\Import::$importHistoryModel.
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by thicolares** [comment] 2018-10-27 04:50
May I? :) I've just reproduced the errors. Can you assign it to me?

**Comment by thicolares** [comment] 2018-10-27 05:43
After cleaning up the first error, I got:
```
  148    Property Magento\ImportExport\Model\Import::$_csvFactory has unknown class                    
         Magento\ImportExport\Model\Export\Adapter\CsvFactor as its type.                              
  158    Property Magento\ImportExport\Model\Import::$_uploaderFactory has unknown class               
         Magento\MediaStorage\Model\File\UploaderFactory as its type.                                  
  203    Parameter $csvFactory of method Magento\ImportExport\Model\Import::__construct() has invalid  
         typehint type Magento\ImportExport\Model\Export\Adapter\CsvFactory.                           
  203    Parameter $uploaderFactory of method Magento\ImportExport\Model\Import::__construct() has     
         invalid typehint type Magento\MediaStorage\Model\File\UploaderFactory.
```   

I could not found the \Magento\MediaStorage\Model\File\UploaderFactory nor its history. Do you know about it?

**Comment by denispapec** [comment] 2018-10-28 21:53
Hi @colares,
\Magento\MediaStorage\Model\File\UploaderFactory is a [factory class](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/factories.html), created during Magento compilation from [Uploader](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/MediaStorage/Model/File/Uploader.php) class.
After cleaning up errors from initial comments, compiling Magento code, there shouldn't be any more phpstan errors from this file.

**Comment by thicolares** [comment] 2018-10-28 23:33
Mm.. Thank you, @denispapec! In fact I suspected that I had forgotten some step, since I did not find the class in the repository. I will compile Magento this time. Btw, that's my first time ever I'm interacting with a Magento's code :)

**Comment by dmanners** [comment] 2018-10-29 10:21
Hi @colares thanks for the question. Yes the factory classes during compilation sorry for not adding that information in original ticket.

**Closed as completed** 2019-04-29 15:41 UTC
Labels: help wanted, good first issue
