### ISSUE TITLE
Product attribute accepted via admin interface but cannot relate via import csv

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#56] opened 2017-11-06 17:26 UTC
_From @LiamFielding on July 18, 2016 13:25_

Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a dropdown attribute with values: '5µ, 10µ, 15µ...'
3. Attempt to add those accepted attribute values with attribute to a product via csv.

Expected result
1. Product given attribute and attribute value correctly recognised as it is accepted in interface.

Actual result
1. Value not recognised.

I believe this is due to HTML encoding or URL encoding, or whatever encoding is used to process the spreadsheet, though I may be mistaken.

_Copied from original issue: magento/magento2#5690_

**Comment by piotrekkaminski** [comment] 2017-11-06 17:26
_From @LiamFielding on August 8, 2016 13:30_

It is a problem with the micron/other symbols. They have to match but the importer parses the value so it no longer matches the attribute label.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:26
_From @veloraven on August 9, 2016 8:26_

@LiamFielding I used exactly the same symbol you provided. And I had no problems during import.
Could you please update your develop branch and confirm that the issue is still there?
And if it is, I still need more detailed steps including information, how did you create a file for import? 
Maybe list of some other symbols you have problems with.
Please also provide information about your environment: OS, PHP, MySQL, web browser versions.
And specify if it was clear install or upgrade from some previous version.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:26
_From @LiamFielding on August 9, 2016 8:29_

Your attribute say "Measurement X" has a value in the attribute dropdown (admin) of 5µ what value did you use in your spreadsheet to give the product this attribute value option?

**Comment by piotrekkaminski** [comment] 2017-11-06 17:26
_From @magento-engcom-team on October 17, 2017 13:30_

@LiamFielding, thank you for your report.
We've created internal ticket(s) MAGETWO-82088 to track progress on the issue.

**Comment by TomashKhamlai** [comment] 2017-12-20 17:01
@dmanners, I cannot reproduce this on public 2.3-develop.
### Preconditions:

1. Magento with Sample Data was installed using Vagrant
2. Attribute was created and added to the Default attribute set
3. 4 products with 3 different values tor the created attribute were created and assigned to the same category.
4. Products that were in the category with id=41 were exported

### Steps to reproduce:

1. Create 3 more products in the CSV. Give them unique values such as SKU and URL key and save the file
2. Import the modified file

### Actual result:
Products were successfully imported

**Comment by dmanners** [comment] 2018-01-02 15:01
Thank you @TomashKhamlai for the information. I will close this now as it is not reproducible on latest version

**Closed by dmanners** 2018-01-02 15:01 UTC
Labels: 2.1.x, 2.2.x, 2.3.x, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x
