### ISSUE TITLE
Importing 'Customers Main File'

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#44] opened 2017-11-06 17:13 UTC
_From @WaPoNe on March 6, 2017 10:36_

Error received trying to import the 'Customers Main File' sample file.

### Preconditions

1. Magento Version 2.1.5 or 2.1.4

### Steps to reproduce

1. Go to 'System' > 'Data Transfer' > 'Import'
2. Select 'Customers Main File' as 'Entity Type'
3. Click on 'Download Sample File' link
4. Select the file downloaded to import

### Expected result

1. Import activity worked fine and customers data imported correctly.

### Actual result

'reward_update_notification' and 'reward_warning_notification' are invalid attributes.

![importing customers](https://cloud.githubusercontent.com/assets/11091926/23606378/c01d5220-0260-11e7-8cb2-2227941de019.png)

_Copied from original issue: magento/magento2#8798_

**Comment by piotrekkaminski** [comment] 2017-11-06 17:13
_From @Andrii-Deineha on June 30, 2017 8:41_

@WaPoNe Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-70369.

**Comment by piotrekkaminski** [comment] 2017-11-06 17:13
_From @magento-engcom-team on October 4, 2017 8:30_

@WaPoNe, thank you for your report.
We've created internal ticket(s) MAGETWO-70369 to track progress on the issue.

**Comment by dmanners** [comment] 2017-12-01 15:19
Looks like this could be the same issue as https://github.com/magento-engcom/import-export-improvements/issues/53 we should double check and then close one so we are not duplicating issues.

**Comment by TomashKhamlai** [comment] 2017-12-26 14:22
@dmanners, reproduced

**Comment by dmanners** [comment] 2018-07-23 14:26
Issue fixed in PR https://github.com/magento-engcom/import-export-improvements/pull/110

**Closed as completed by dmanners** 2018-07-23 14:26 UTC
