### ISSUE TITLE
Import doesn't allow to set default value per store view (dropdown fields)

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#91] opened 2018-01-03 16:03 UTC
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Two store views are created (english and chinese)
3. Products are imported from attached file 
[import_productsoftwostoresdata.csv.zip](https://github.com/magento/magento2/files/1560048/import_productsoftwostoresdata.csv.zip)

### Steps to reproduce
1. Log in to Admin
2. Go to Catalog > Products
3. Open product name4
4. Go to Advanced Settings > Auto Settings
5. Check Visibility field - it has value Catalog 
6. Switch store view to english or chinese

### Expected result
Field Visibility should have the same value as on Default store: Catalog

### Actual result
Field Visibility has value: Catalog, Search

Import file has empty value for this option per store views and it should be copied from default store.
The same issue with all dropdown fields (see also fields **Display Product Options In** in Design section )

**Comment by piotrekkaminski** [comment] 2018-01-03 16:05
Related commits: https://github.com/madbounce/magento2/commit/5acc5f9c8e71d039523ebe544ef1805582c22e10
https://github.com/madbounce/magento2/commit/101aa681d69df50fcd223ee2ade9483c49cd3130

https://github.com/magento/magento2/pull/12754

**Comment by dmanners** [comment] 2018-01-17 08:19
This is a duplicate of https://github.com/magento-engcom/import-export-improvements/issues/61

**Closed as completed by dmanners** 2018-01-17 08:19 UTC
