### ISSUE TITLE
2.2 Importing Group Products No Longer Works

### ISSUE THREAD

**Issue by piotrekkaminski** [magento-engcom/import-export-improvements#76] opened 2018-01-03 15:54 UTC
_From @mzenner1 on December 18, 2017 17:16_

As of 2.2, group products no longer import properly.  Using the sample data given on the system->import page, it will import the group product (the product type is correct), but no longer associate the simple products to the grouped product.  This was confirmed working in 2.1.7, but looks to be broken in 2.2.1 and 2.2.2.

_Copied from original issue: magento/magento2#12793_

**Comment by piotrekkaminski** [comment] 2018-01-03 15:54
_From @magento-engcom-team on December 21, 2017 6:37_

@mzenner1, thank you for your report.
We've created internal ticket(s) MAGETWO-85900 to track progress on the issue.

**Comment by piotrekkaminski** [comment] 2018-01-03 15:54
_From @PieterCappelle on December 21, 2017 21:16_

Hi @mzenner1 , I've created PR to fix this issue. Currently only for 2.3-develop branch. If accepted I'll create backport to 2.2-develop branch.

Issue has been created because of new functionality in 2.2 & 2.3 for duplicate SKU's. Every SKU is lowercased. In this function it was forgotten to change SKU to lowercase.

@dmanners Could you add import/export label to this issue. Thanks!

**Comment by piotrekkaminski** [comment] 2018-01-03 15:54
_From @sasilinux on December 22, 2017 4:13_

@mzenner1 - Have you ever got a chance to solve this issue. If you found any solution, please let me know. Thanks

**Comment by piotrekkaminski** [comment] 2018-01-03 15:54
_From @PieterCappelle on December 22, 2017 6:50_

@sasilinux I fixed in that PR. Just need to fix unit test but is easy. Will fix it.

**Comment by piotrekkaminski** [comment] 2018-01-03 15:54
_From @mzeis on December 27, 2017 12:58_

@PieterCappelle @dmanners FYI I added the Import/Export label.

**Comment by dmanners** [comment] 2018-01-17 08:37
Duplicate of https://github.com/magento-engcom/import-export-improvements/issues/34

**Closed as completed by dmanners** 2018-01-17 08:37 UTC
Labels: acknowledged
